### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Wilexcess** [CroissantDuNord/we-to-lively#2]
![image](https://github.com/CroissantDuNord/we-to-lively/assets/81816727/5622391b-e730-4a34-83aa-6f580375aeb1)
typo

**Comment by SirHaxe** [comment]
currently working on some features
is there a specific reason why you are using the image as a gui, and not tkinter itself? @CroissantDuNord

**Comment by CroissantDuNord** [comment]
I have more design freedom with images. Its only used for that part. But it does make modifications harder

**Comment by CroissantDuNord** [comment]
Fixed in the last release (new ui)
