### ISSUE TITLE
about .pkg

### ISSUE THREAD

**Issue by uhhhzedo** [CroissantDuNord/we-to-lively#3]
i don't get it, what to do after extract the pkg file?

**Comment by CroissantDuNord** [comment]
You can browse the files of the wallpaper, can you view file like mp4, png... to search for them you can type "*.png" in the search bar, this will only show the png file, you can do the same for mp4 and any other format 

Exemple:
![image](https://github.com/CroissantDuNord/we-to-lively/assets/79372025/5e7e7866-d3d7-4db7-aab3-394fe45da3fd)
