### ISSUE TITLE
after converting the .zip file

### ISSUE THREAD

**Issue by steak20** [CroissantDuNord/we-to-lively#5]
after converting the .zip file, an folder opens with alot of files, wheres the wallpaper?

https://prnt.sc/ROZoiqeWHQPz

**Comment by Sankha-Suvra** [comment]
@CroissantDuNord this is my question too. some .zip file doesn't contains .mp4 file in it therefore wetolively asking us to use RePKG. and after using that a folder is created with all the items in it(just like @steak20 provided). how to get the .mp4 file out of it?

**Comment by CroissantDuNord** [comment]
RePKG was removed on the last version, it was not ready for the users, I'm going to re-add it (0.4), but the program will do the work, and only give you the right file (png / mp4)
