### ISSUE TITLE
v1.3 reported as Trojan:Win32/ScarletFlash.A by Windows Defender

### ISSUE THREAD

**Issue by laurorual** [CroissantDuNord/we-to-lively#6]
Just tried downloading v1.3 but Windows Defender blocked it, saying it was a "Trojan:Win32/ScarletFlash.A".
Don't know if it is a false positive, but sure is something to look into.

**Comment by SirHaxe** [comment]
Check the main.py, the exe is just converted python
Interestingly, VirusTotal flags some other stuff too, not sure why though

**Comment by Caddy8970** [comment]
False Positive, check source code

**Comment by CroissantDuNord** [comment]
I can confirm this is a false posivte, Im gonna try to check how a converted the program to .exe for now, just the source code if you dont want to flag the file as false positive

**Comment by CroissantDuNord** [comment]
Issue fixed with 1.4 the console is no longer hidden or windows will flag it as a virus also it's no longer compiled as one file
![image](https://github.com/CroissantDuNord/we-to-lively/assets/79372025/0e4fd86f-3761-40ae-b23e-a30a2dea5635)
